### ISSUE TITLE
hi, is there a train module in this project?

### ISSUE THREAD

**Issue by happywmzzz** [ldf921/flownext#1]
I con't find it, i mean the  process of training flownetS on flying chairs or sintel

thx

**Comment by happywmzzz** [comment]
and when using flying chairs dataset, is there something to do with this dataset? I use your 'binary reader.load' make an error 'need more than 0 value to unpack'

**Comment by ldf921** [comment]
I am still developing this project, the code contains a lot of hard code path and data formats, I will clean to code for public when the whole the project is finished. If you really need this code at this time, please contact me through email.
